monitor.alsa.rules = [
  {
    matches = [
      { "device.name", "matches", "alsa_card.*" }
    ]
    actions = {
      update-props = {
        "device.profile" = "Analog Stereo"
      }
    }
  }
]