monitor.alsa.rules = [
  {
    matches = [
      { "node.name", "matches", "alsa_output.*" }
    ]
    actions = {
      update-props = {
        "node.nick" = "Speakers"
        "priority.driver" = 100
        "priority.session" = 100
      }
    }
  }
]