return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      integrations = {
        cmp = true,
        gitsigns = true,
        mason = true,
        mini = true,
        noice = true,
        notify = true,
        snacks = true,
        telescope = true,
        treesitter = true,
        which_key = true,
      },
    },
  },
  {
    "nvim-lualine/lualine.nvim",
    opts = {
      options = { theme = "catppuccin" },
    },
  },
  {
    "christoomey/vim-tmux-navigator",
    lazy = false,
  },
  {
    "akinsho/toggleterm.nvim",
    version = "*",
    opts = {
      size = 18,
      shade_terminals = true,
      direction = "horizontal",
    },
  },
  {
    "williamboman/mason.nvim",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "ansible-language-server",
        "bash-language-server",
        "dockerfile-language-server",
        "eslint-lsp",
        "hadolint",
        "helm-ls",
        "html-lsp",
        "json-lsp",
        "lua-language-server",
        "marksman",
        "prettierd",
        "shellcheck",
        "shfmt",
        "stylua",
        "taplo",
        "terraform-ls",
        "tflint",
        "typescript-language-server",
        "yaml-language-server",
      })
    end,
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        ansiblels = {},
        bashls = {},
        cssls = {},
        dockerls = {},
        eslint = {},
        helm_ls = {},
        html = {},
        jsonls = {},
        lua_ls = {},
        taplo = {},
        terraformls = {},
        tflint = {},
        ts_ls = {},
        yamlls = {},
      },
    },
  },
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        bash = { "shfmt" },
        css = { "prettierd", "prettier" },
        hcl = { "terraform_fmt" },
        html = { "prettierd", "prettier" },
        javascript = { "prettierd", "prettier" },
        javascriptreact = { "prettierd", "prettier" },
        json = { "prettierd", "prettier" },
        lua = { "stylua" },
        markdown = { "prettierd", "prettier" },
        sh = { "shfmt" },
        terraform = { "terraform_fmt" },
        toml = { "taplo" },
        typescript = { "prettierd", "prettier" },
        typescriptreact = { "prettierd", "prettier" },
        yaml = { "prettierd", "prettier" },
        zsh = { "shfmt" },
      },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      vim.list_extend(opts.ensure_installed, {
        "bash",
        "css",
        "dockerfile",
        "gitignore",
        "hcl",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "scss",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "yaml",
      })
    end,
  },
}
