unbind r
bind r source-file ~/.tmux.conf

# Mouse
set -g mouse on
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# Key binds

# Status bar possitin
set-option -g status-position top
# Colors
set -g default-terminal "xterm-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set -as terminal-features ",xterm-256color:RGB"
set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

# set -g default-terminal "xterm-kitty"
# set-option -sa terminal-features ',xterm-kitty:RGB'
# set -as terminal-features ",:xterm-kitty:RGB"
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'
#

# Tmux neovim naviagator
# decide whether we're in a Vim process
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'

if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -n 'C-Space' if-shell "$is_vim" 'send-keys C-Space' 'select-pane -t:.+'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l
bind-key -T copy-mode-vi 'C-Space' select-pane -t:.+

# Catppuccin theme
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_status_style "rounded"
set -gu @catppuccin_window_current_left_separator
set -gu @catppuccin_window_current_middle_separator
set -gu @catppuccin_window_current_right_separator

set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_text " #W"

set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text " #W"

set -g @catppuccin_status_modules_right "directory session"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "icon"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_flavor "macchiato"

set -g @catppuccin_directory_text "#{pane_current_path}"

# Remap the split windows bind-key
# Remap 'h' to split horizontally (same as "%")
bind h split-window -h -c "#{pane_current_path}"

# Remap 'v' to split vertically (same as '""')
bind v split-window -v -p 30 -c "#{pane_current_path}"

# Index id start from 1
set -g base-index 1
set -g renumber-windows on


# Reduce escape-time for neovim
set -sg escape-time 10

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'catppuccin/tmux#latest'

set -g @plugin 'christoomey/vim-tmux-navigator'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Keep user-assigned window names stable across pane/window switches.
set-window-option -g automatic-rename off
set-option -g allow-rename off
