# Font configuration
font_family JetBrains Mono
font_size 10.0

# vim:ft=kitty

## name:     Catppuccin Kitty Macchiato
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/macchiato.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #cad3f5
background              #24273a
selection_foreground    #24273a
selection_background    #f4dbd6

# Cursor colors
cursor                  #f4dbd6
cursor_text_color       #24273a

# URL underline color when hovering with mouse
url_color               #f4dbd6

# Kitty window border colors
active_border_color     #b8c0e0
inactive_border_color   #5b6078
bell_border_color       #eed49f

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Colors for marks (marked text in the terminal)
mark1_foreground #24273a
mark1_background #b8c0e0
mark2_foreground #24273a
mark2_background #c6a0f6
mark3_foreground #24273a
mark3_background #7dc4e4

# The 16 terminal colors

# black
color0 #494d64
color8 #5b6078

# red
color1 #ed8796
color9 #ed8796

# green
color2  #a6da95
color10 #a6da95

# yellow
color3  #eed49f
color11 #eed49f

# blue
color4  #8aadf4
color12 #8aadf4

# magenta
color5  #f5bde6
color13 #f5bde6

# cyan
color6  #8bd5ca
color14 #8bd5ca

# white
color7  #b8c0e0
color15 #a5adcb

# Colors for the tab bar
tab_bar_background #181926
active_tab_background #c6a0f6
active_tab_foreground #181926
inactive_tab_background #363a4f
inactive_tab_foreground #cad3f5
inactive_tab_hover_background #5b6078
inactive_tab_hover_foreground #f4dbd6
new_tab_background #8aadf4
new_tab_foreground #181926
new_tab_hover_background #7dc4e4
new_tab_hover_foreground #181926

# Add padding around the window and tab bar
padding_width 5 5 5 5
tab_bar_edge_padding 5 5

# Transparent tab bar background (optional)
# tab_bar_background_opacity 0

# Keybindings for tab navigation
map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab

# Hide tab bar when only one tab is open (optional)
hide_tab_bar_when_only_one_tab yes

#Disable the bell sound
enable_audio_bell no

# Keybindings
map ctrl+shift+r kitten themes --reload

# Map Alt+j and Alt+k for down and up
map alt+j send_text all \x1b[B
map alt+k send_text all \x1b[A

# Map Alt+h and Alt+l for left and right word movement
map alt+h send_text all \x1b[1;3D
map alt+l send_text all \x1b[1;3C

# Map Alt+h and Alt+l for left and right word movement
map alt+g send_text all \x1b[D
map alt+; send_text all \x1b[C
