# Font configuration
font_family JetBrains Mono
font_size 10.0

# vim:ft=kitty

## name:     Catppuccin Kitty Frappé
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/frappe.conf
## blurb:    Soothing pastel theme for the high-spirited!



# The basic colors
foreground              #c6d0f5
background              #303446
selection_foreground    #303446
selection_background    #f2d5cf

# Cursor colors
cursor                  #f2d5cf
cursor_text_color       #303446

# URL underline color when hovering with mouse
url_color               #f2d5cf

# Kitty window border colors
active_border_color     #babbf1
inactive_border_color   #737994
bell_border_color       #e5c890

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #232634
active_tab_background   #ca9ee6
inactive_tab_foreground #c6d0f5
inactive_tab_background #292c3c
tab_bar_background      #232634

# Colors for marks (marked text in the terminal)
mark1_foreground #303446
mark1_background #babbf1
mark2_foreground #303446
mark2_background #ca9ee6
mark3_foreground #303446
mark3_background #85c1dc

# The 16 terminal colors

# black
color0 #51576d
color8 #626880

# red
color1 #e78284
color9 #e78284

# green
color2  #a6d189
color10 #a6d189

# yellow
color3  #e5c890
color11 #e5c890

# blue
color4  #8caaee
color12 #8caaee

# magenta
color5  #f4b8e4
color13 #f4b8e4

# cyan
color6  #81c8be
color14 #81c8be

# white
color7  #b5bfe2
color15 #a5adce

# Colors for the tab bar
tab_bar_background #1e1e2e
active_tab_background #f38ba8
active_tab_foreground #1e1e2e
inactive_tab_background #45475a
inactive_tab_foreground #cdd6f4
inactive_tab_hover_background #585b70
inactive_tab_hover_foreground #f5e0dc
new_tab_background #89b4fa
new_tab_foreground #1e1e2e
new_tab_hover_background #74c7ec
new_tab_hover_foreground #1e1e2e

# Add padding around the window and tab bar
padding_width 5 5 5 5
tab_bar_edge_padding 5 5

# Hide borders in stacked and tabbed layouts
hide_edge_borders smart
# Set the gaps between windows
gaps inner 10
gaps outer 10

# Transparent tab bar background (optional)
# tab_bar_background_opacity 0

# Keybindings for tab navigation
map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab

# Hide tab bar when only one tab is open (optional)
hide_tab_bar_when_only_one_tab yes

# Navigate to the next tab (right)
map ctrl+shift+] next_tab

# Navigate to the previous tab (left)
map ctrl+shift+[ previous_tab

#Disable the bell sound
enable_audio_bell no

# Keybindings
map ctrl+shift+r kitten themes --reload

# Map Alt+j and Alt+k for down and up
map alt+j send_text all \x1b[B
map alt+k send_text all \x1b[A

# Map Alt+h and Alt+l for left and right word movement
map alt+h send_text all \x1b[1;3D
map alt+l send_text all \x1b[1;3C

# Map Alt+h and Alt+l for left and right word movement
map alt+g send_text all \x1b[D
map alt+; send_text all \x1b[C


